// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC360Pk2mNycfxXXTGPZbrgoRkfDnuWaqs',
    appId: '1:775290642891:web:7103ebf2141c0ad9d1164e',
    messagingSenderId: '775290642891',
    projectId: 'flutter-projects-b6cca',
    authDomain: 'flutter-projects-b6cca.firebaseapp.com',
    databaseURL:
        'https://flutter-projects-b6cca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-projects-b6cca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzYoGyez9BAMxrNyTnmcigGW8pY7JG4VA',
    appId: '1:775290642891:android:2c880a1a48fe5217d1164e',
    messagingSenderId: '775290642891',
    projectId: 'flutter-projects-b6cca',
    databaseURL:
        'https://flutter-projects-b6cca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-projects-b6cca.appspot.com',
  );
}
